# Generated by Django 4.2.16 on 2024-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
                ("year_founded", models.IntegerField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("size_range", models.CharField(blank=True, max_length=50, null=True)),
                ("locality", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("linked_url", models.URLField(blank=True, max_length=500, null=True)),
                ("current_employee_estimate", models.CharField(blank=True, max_length=255, null=True)),
                ("total_employee_estimate", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
