# Generated by Django 4.2.16 on 2024-10-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalyst_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company", old_name="linked_url", new_name="linkedin_url",
        ),
    ]
